### ISSUE TITLE
rdf-canonize v0.2.1 not compatible with Node.js v8.9.1(LTS)?

### ISSUE THREAD

**Issue by nitmws** [digitalbazaar/rdf-canonize#2]
I'm using [jsonld.js](https://github.com/digitalbazaar/jsonld.js) with a Node.js project and this module uses this rdf-canonize. This worked well since summer 2017 using the 6.x LTS version.
Now I have updated my Node.js to the 8.x LTS version (v8.9.1) and rdf-canonize throws an error and fails to update/install. This is what I get returned:

```
npm install rdf-canonize

> rdf-canonize@0.2.1 install ...(my project's root folder)...\node_modules\rdf-canonize
> node-gyp rebuild


....\node_modules\rdf-canonize>if not defined npm_config_node_gyp (node "....\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
These projects from the projects folder are generated now (<<- translated to English!)
  IdentifierIssuer.cc
  MessageDigest.cc
  NQuads.cc
  addon.cc
  urdna2015.cc
  win_delay_load_hook.cc
..\lib\native\MessageDigest.cc(56): error C2131: expression did not evaluate to a constant [....\node_modules\rdf-canonize\build\urdna2015.vcxproj]
  ..\lib\native\MessageDigest.cc(56): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\lib\native\MessageDigest.cc(56): note: see usage of 'length'
..\lib\native\MessageDigest.cc(68): error C2131: expression did not evaluate to a constant [....\node_modules\rdf-canonize\build\urdna2015.vcxproj]
  ..\lib\native\MessageDigest.cc(68): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\lib\native\MessageDigest.cc(68): note: see usage of 'length'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (....\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "....\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ....\node_modules\rdf-canonize
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rdf-canonize@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rdf-canonize@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Having a look at this repository's [CHANGELOG](https://github.com/digitalbazaar/rdf-canonize/blob/master/CHANGELOG.md): 
* release 0.2.0 notes "Support Node.js 6" - does that mean v8 is not supported?
* 0.2.1 notes that binding.gyp is distributed, may this be the source of this problem?

**Comment by davidlehn** [comment]
It should work fine with node 6 and 8.  We recently updated rdf-canonize with a native module for use in node that has nice speedups.  The bindings file is needed so that can build.  It looks like your c++ compiler doesn't like the use of non-const array size initializers.  I just published 0.2.2 with a patch that makes those "const".  Please test.  It works fine either way with gcc, but I have no way to test microsoft compilers.

**Comment by nitmws** [comment]
I've tried to install 0.2.2 on my Windows computer - with the same error.
This error "error C2131: expression did not evaluate to a constant" has caused already some confusion in the MS community, e.g. https://connect.microsoft.com/VisualStudio/feedback/details/1596224/erroneous-error-c2131-expression-did-not-evaluate-to-a-constant. But that was raised in July 2015 and in September 2015 the Visual C++ Team claimed the error is fixed.
Unfortunately it is hard to find out which MS C/C++ compiler is used on my computer for the compiling by node-gyp, by my investigations it is a version 14.0. ...
I'm no C++ expert and simply ask: is there a way to deal with constant differently to avoid errors by the MS compiler?

**Comment by davidlehn** [comment]
It looks like variable length arrays are a C99 feature but not supported by C++ yet.  g++ supports this just fine though.  I refactored to hopefully avoid the issue.  Please try with 0.2.3.
