### ISSUE TITLE
Most URDNA2015 Synchronous tests are not being checked

### ISSUE THREAD

**Issue by davidlj95** [digitalbazaar/rdf-canonize#20]
# Background
We (@btcassessors) are developing a Java implementation of the [RDF canonization spec](https://github.com/json-ld/normalization). We were running the tests to check how this library behaves  (as it passes all tests) to find the buggy behaviour in our implementation.

# Reproduce the issue
While debugging [the tests file `test.js`](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/test/test.js), we discovered that the [input RDF dataset in (`jsParams`)](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/test/test.js#L259) of the test for the URDNA2015 synchronous tests is already a canonized RDF dataset.

The first test with this issue is [`manifest-urdna2015#test003`](https://github.com/json-ld/normalization/blob/gh-pages/tests/test003-in.nq) (as this is the first test whose input RDF dataset is different from its expected canonized RDF dataset). 

After executing the async version of the test, the sync version of the test has a [`jsParams` argument value RDF dataset](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/test/test.js#L259) whose first quad is already a canonical blank node identifier `_:c14n0` instead of the original test input blank node identifier (`_:b0`).

## In webstorm
Place two breakpoints in [the tests file `test.js`](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/test/test.js) at lines [248](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/test/test.js#L248) and [259](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/test/test.js#L259), with a breakpoint condition to match the third test (`this.test.title.includes("manifest-urdna2015#test003")`).

Run the tests (`mocha --check-leaks`). The first breakpoint at line `248` (`async test`) triggers. The subject of the first quad of the RDF dataset to canonize is `_:b0`. Continue the execution (<kbd>F9</kbd>). The breakpoint at line `259` triggers. Now the same subject is already canonized, as the value is `_:c14n0`. So the canonization test will get as input a canonized RDF dataset, so the test is not testing properly the canonization as the input is already canonized.

# The issue
Both [`URDNA2015.js`](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/lib/URGNA2015.js) and [`URDNA2015Sync.js`](https://github.com/digitalbazaar/rdf-canonize/blob/v1.0.2/lib/URGNA2015Sync.js) **do not create a deep copy of the input RDF dataset to canonize**. Then, the input dataset gets modified (canonized) and when the other version either `sync` or `async`, is tested, the input is already canonized. Actually, the `async` gets executed first, so `sync` test input is an already canonized RDF dataset. If we switch the source code order, the same issue happens (viceversa).

I've not tested if the same happens for `URGNA2012` tests, but it seems that is also happening as the implementation is similar (indeed `URGNA2012` class extends `URDNA2015` one)

# Proposed solution
Creating a deep copy using `JSON.parse(JSON.stringify(inputRDFDataset))` at the beginning of each canonizer could be a solution, but I don't know if there's a better way (mostly in performance) to do the same.

PS: Thanks to @ccebrecos for helping me in the process

**Comment by davidlehn** [comment]
I doubt that mutating the input was intentional, unless it was for optimization purposes.  Fixing the tests by copying inputs would cover that issue up.  A better approach would be to first see if it's a simple fix in the code to not change the input.  Tests for that would be good too.

This didn't cause any correctness issues did it?

**Comment by davidlehn** [comment]
Also related to your implementation, we'd really like feedback on the spec itself.  Ideally, an implementation should be able to be written from the spec text alone.  We really need feedback on text that could use improvement.  We should also add a section to the json-ld.org homepage tracking canonize implementations, and would be happy to add yours.

**Comment by davidlj95** [comment]
I think the easiest fix is to create a copy of the input RDF dataset prior to sending it to the canonize function(s). This way tests will always test the uncanonized RDF dataset (as it should be). 

It didn't cause any correctness issues AFAIK. When I created a copy prior to sending the RDF dataset to canonize so that both tests get an uncanonized RDF dataset as input all tests passed properly both in async and sync versions.

I can create a PR to add the few lines that create a copy of the RDF datasets prior to sending them to test so that both versions sync and async get tested properly.

**Comment by davidlj95** [comment]
As for the implementation, we're using https://github.com/boumba100/JsonldAndroid as a base, without 

When the project we're developing enters in the tests phase, we'll review the spec and implementation in depth and provide feedback!

**Comment by davidlehn** [comment]
The similar sync and async code explicitly "optimizes away the copy" which is what causes the input to be changed:
https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015Sync.js#L176
https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/URDNA2015.js#L211
```js
              // 7.1) Create a copy, quad copy, of quad and replace any existing
              // blank node identifiers using the canonical identifiers
              // previously issued by canonical issuer.
              // Note: We optimize away the copy here.
              // ...
                  component.value = self.canonicalIssuer.getId(component.value);
```
@dlongley This optimization changes the input dataset.  Was that the intent?

**Comment by davidlehn** [comment]
There's a ton of optimization opportunities everywhere in that code. ;-)  For this case, it's just munging a quad, serializing it, then throwing it out.  Could replace that process and weird forEachComponent function with a simple function and a (new) `NQuads.serializeQuadParts(f(s), p, f(o), f(g))` call.  Would avoid a loop, calls, param checks, and object packing and unpacking, and input would be untouched.  Unless there is some reason to do that component loop vs direct logic?

**Comment by dlongley** [comment]
> This optimization changes the input dataset. Was that the intent?

I don't recall. There's a lot of potential optimizations as you said -- a few optimization experiments were started on a few branches in this repo but the time has never been there to finish them. Would love to see more optimizations -- and if there's a better one that doesn't mutate the inputs, great.

**Comment by davidlehn** [comment]
I took a quick stab over in https://github.com/digitalbazaar/rdf-canonize/pull/21.
