### ISSUE TITLE
Switch to core-js@3

### ISSUE THREAD

**Issue by nileshpatra** [digitalbazaar/rdf-canonize#26]
core-js@2 is deprecated, and on directly using core-js@3 with the package, the build and tests fail.
Switching to a newer version should be a good idea.

**Comment by mandyvenables** [comment]
@davidlehn There is a PR on [this repo] (https://github.com/digitalbazaar/rdf-canonize/issues/26) and on [jsonld](https://github.com/digitalbazaar/jsonld.js/pull/361) about updating from the deprecated version of core-js.

**Comment by davidlehn** [comment]
@mandyvenables Yes.  I was planning to hold off on such updates until 1.1 support and tests are finished in jsonld package.  Then core-js and all the other things will be updated at once.  (It's all taking longer than expected, of course.)  There were valid reasons for this... avoiding breaking support of old Node versions or something.  I'm forgetting the details, and maybe that's not relevant anymore, but still seems like it can wait a bit longer.

**Comment by dmitrizagidulin** [comment]
Just as heads up, jsonld.js has now upgraded to core-js@3 (thanks to @nileshpatra) as of npm version `4.0.1`.

**Comment by davidlehn** [comment]
Closing.  The bundle build in this package was removed in 3.0.0.
