### ISSUE TITLE
Drop support for node 6 and 8 in next major release

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/rdf-canonize#34]
Node 6 and 8 have already been removed from CI.  As these version of Node.js are EOL, we will remove support for them in the next major release.

CI was failing on node 6 due to an ES6 spread operator in the test framework.  see: https://travis-ci.org/github/digitalbazaar/rdf-canonize/builds/731741720

**Comment by davidlehn** [comment]
Done in 3.0.0.
