### ISSUE TITLE
Native build necessary even when using browser-based

### ISSUE THREAD

**Issue by peacememories** [digitalbazaar/rdf-canonize#5]
We recently updated our dependency on [jsonld](https://www.npmjs.com/package/jsonld).
An unwanted side-effect of this is unfortunately that `rdf-canonize` needs native building via `node-gyp`. 

Requiring `windows-build-tools` on our developer machines is difficult because of certain security restrictions, so the setup has been rather problematic, especially since we have no need for the native version of the code. We are running everything in the browser after all.

Would it be possible to opt out of the `node-gyp` build when only needing the js version of the package?

**Comment by davidlehn** [comment]
This is causing trouble for a number of people.  What we're likely to do is pull out the native code into a new module, and higher level apps will just have to know to install it to get the native speedups.  If anyone knows of a better solution, please speak up.

**Comment by peacememories** [comment]
Another option would be to go the way of `node-sass` and provide caches for binaries

**Comment by davidlehn** [comment]
The optional dep is a possibility, but a concern is that developers with build tools installed will see a certain performance level, then someone else will install a package and not even notice the build failure, and then there will be confusion about the slower performance.  Maybe this isn't a real issue?

I think the webpack code will be fine.  It doesn't pull in native code now, just need to adapt to changes.

Hosting binaries sounds like a horror show for maintainers!

**Comment by davidlehn** [comment]
I made a test split out using an "optionalDependency" to a native-only version.  Feel free to test and leave feedback if it works in your environment.
https://github.com/digitalbazaar/rdf-canonize/tree/opt-native

**Comment by peacememories** [comment]
I'll have to ask one of my colleagues to test this on Tuesday (I've personally switched my development machine over to linux), but this sounds exactly like what we needed :) I'll keep you posted.

**Comment by peacememories** [comment]
I have so far only been able to test the branch on my linux machine since testing it properly would mean breaking a build environment of one of my developers' machines.
What i did:
1. Installed our project dependencies as normal with `npm i`
2. Removed the `node_modules/rdf-canonize` folder
3. Cloned the branch in its place
4. Ran `npm i` in the newly cloned `rdf-canonize` folder

Unfortunately it seems that building the package failed with the following while running `build-webpack`:

```
ERROR in rdf-canonize.min.js from UglifyJs
Unexpected token: operator (>) [rdf-canonize.min.js:211,6]
```

**Comment by nichtich** [comment]
I also get build errors on Ubunty trusty (on travis-ci) with node v10.12.0. Splitting up the native implementation as optional would help.

**Comment by davidlehn** [comment]
The 0.3.0 release splits the native code out into an optional rdf-canonize-native package. I think that will avoid people seeing failures to install, though the native bindings might fail to build and the code will fallback to the js implementation.

**Comment by davidlehn** [comment]
jsonld.js 1.2.0 released using rdf-canonize.  Not a perfect solution but hopefully will help with the build issues.

**Comment by danbri** [comment]
Found my way here via 

> WARNING in ./node_modules/rdf-canonize/lib/index.js 53:22-52
Module not found: Error: Can't resolve 'rdf-canonize-native' in '/Users/danbri/working/kgx/schemarama/core/node_modules/rdf-canonize/lib'
 @ ./node_modules/rdf-canonize/index.js 8:0-33
 @ ./node_modules/jsonld/lib/jsonld.js 52:15-38
 @ ./node_modules/jsonld/lib/index.js 8:0-36
 @ ./parser.js 24:13-30
 @ ./index.js 19:17-50 20:15-46 21:18-52 22:13-42 23:15-46

...while trying to update https://github.com/google/schemarama/ dependencies.

**Comment by mattcollier** [comment]
@danbri You should be able to safely ignore that warning.  `rdf-canonize-native` is optionally required here:

https://github.com/digitalbazaar/rdf-canonize/blob/master/lib/index.js#L42-L46

**Comment by danbri** [comment]
Thanks. Is it webpack trying to be clever but not checking for try/catch?

**Comment by davidlehn** [comment]
I think webpack should be able to handle it due to the `browser` override:
https://github.com/digitalbazaar/rdf-canonize/blob/master/package.json#L65
