### ISSUE TITLE
Add `AbortSignal` instance `signal` option to `canonize`

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/rdf-canonize#55]
Check `signal` periodically during hash n-quads to see if the caller has aborted the canonize operation. This will allow the caller to do things like this:

`canonize({..., {signal: AbortSignal.timeout(1000)}})`

Causing canonize to timeout if it doesn't complete in one second.

See: https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal

**Comment by dlongley** [comment]
Consider setting the default `signal` to `AbortSignal.timeout(1000)` as well.

**Comment by dlongley** [comment]
Note: The signal should only be checked once the `maxDeepIterations` number has been hit and it should default to `0` so that the signal is always checked by default when hash N-degree quads is used.

**Comment by davidlehn** [comment]
Added in v4.0.0.
